Repository UBC-MDS/portugal_white_wine_quality_predictor_py, pull requests merged in 2023-12, with the labels that each got.

#11 Update env file for Milestone3
  environment.yml
Labels: enhancement, announce

#15 Added CC By 4.0 on LICENSE file
  LICENSE
Labels: documentation, announce

#19 Added docker-compose.yml
  docker-compose.yml
Labels: documentation, enhancement

#21 Added link to docker when pull request
  .github/workflows/docker-publish.yml
Labels: bug, enhancement

#22 Update env
  environment.yml
Labels: announce

#16 Update README.md by changed Usage and adjusted all links
  README.md
Labels: documentation, enhancement, help wanted, announce

#23 Added trigger to push to dockerhub when push or pull environment.yml
  .github/workflows/docker-publish.yml
Labels: enhancement, announce

#26 Adjusted the explanation on docker changing process
  README.md
Labels: documentation, announce

#27 minor adjustment: delete unnecessary whitespace line
  environment.yml
Labels: minor adjustment

#28 delete unused part
  README.md
Labels: minor adjustment

#29 Add making reporting features
  data/Raw/wine+quality.zip
  data/Raw/winequality.names
  report/_config.yml
  report/_toc.yml
  report/portugal_white_wine_quality_predictor_report.ipynb
  report/references.bib
  results/figures/histogram_alcohol.png
  results/figures/histogram_chlorides.png
  results/figures/histogram_citric acid.png
  results/figures/histogram_density.png
  results/figures/histogram_fixed acidity.png
  results/figures/histogram_free sulfur dioxide.png
  results/figures/histogram_pH.png
  results/figures/histogram_quality.png
  results/figures/histogram_residual sugar.png
  results/figures/histogram_sulphates.png
  results/figures/histogram_total sulfur dioxide.png
  results/figures/histogram_volatile acidity.png
  results/figures/scatter_matrix.html
  results/figures/scatter_matrix.png
  results/models/best_model.pkl
  results/tables/correlation_matrix.csv
  results/tables/mean_scores.csv
  results/tables/score_table.csv
  results/tables/test_scores.csv
  script/download_and_extract_data.py
  script/eda.py
  script/evaluate_model.py
  script/read_split_and_save.py
  script/test_and_deploy.py
  src/__pycache__/functions.cpython-311.pyc
Labels: enhancement, help wanted, announce

#33 Adjusted Names on License as be suggested by peer reviewer
  LICENSE
Labels: documentation, announce

#35 Changed docker to use latest image
  .github/workflows/docker-publish.yml
  docker-compose.yml
Labels: enhancement, announce

#48 Updated docker-compose.yml and change calling service to be analysis-env
  docker-compose.yml
Labels: announce

#50 Adjusted Makefile for copy html folder to docs folder
  Makefile
Labels: enhancement, announce

#52 Updated Contributing and Code of Conduct
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: documentation, announce

#54 Included conclusion
  report/portugal_white_wine_quality_predictor_report.ipynb
Labels: documentation

#55 Updated report: updated introduction part
  report/portugal_white_wine_quality_predictor_report.ipynb
Labels: documentation, announce
